name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install flake8==6.1.0
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov black flake8
          sudo apt install -y nmap

      # Lint with Flake8
      - name: Lint with Flake8
        run: |
          # Auto-fix trivial whitespace
          find . -name "*.py" -exec sed -i 's/[ \t]*$//' {} \;
          # Run Flake8
          flake8 .

      # Check code formatting with Black
      - name: Check code formatting with Black
        run: |
          black .
          black --check .
        continue-on-error: false

      # Run tests with coverage
      - name: Run tests with coverage
        run: |
          pytest --cov=fnw --cov-report=xml --cov-report=term-missing

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests
          branch: main
          fail_ci_if_error: true