name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov black flake8

      # Lint with Flake8
      - name: Lint with Flake8
        run: flake8 .
        continue-on-error: false

      # Check code formatting with Black
      - name: Check code formatting with Black
        run: black --check .
        continue-on-error: false

      # Autoformat with Black and commit (non-main branches)
      - name: Commit auto-format changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet || git commit -m "Auto-format code with Black"
          git push

      # Run tests with coverage
      - name: Run tests with coverage
        run: |
          pytest --cov=fnw --cov-report=xml --cov-report=term-missing

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests
          branch: main
          fail_ci_if_error: true